package org.androidrescue.helper;

import android.database.Cursor;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.security.MessageDigest;
import java.text.SimpleDateFormat;
import java.util.*;

/** Read-only provider export. All writes are confined to a new export directory. */
public final class ExportEngine {
    public interface Provider {
        Cursor query(String uri) throws Exception;
        InputStream open(String uri) throws Exception;
        String base64(byte[] bytes);
    }
    public interface Progress { void update(String message); }
    private interface RowAction { void process(JSONObject values, JSONObject metadata) throws Exception; }
    private final Provider provider;
    private final Progress progress;
    private final File output;
    private final JSONArray categories = new JSONArray();
    private final JSONArray errors = new JSONArray();
    private final JSONObject report;
    private final String started = now();
    private long exportedRows;
    private long exportedFiles;

    public ExportEngine(Provider provider, Progress progress, File output, JSONObject device) throws Exception {
        this.provider = provider;
        this.progress = progress;
        this.output = output;
        this.report = new JSONObject();
        report.put("schemaVersion", 1);
        report.put("startedUtc", started);
        report.put("device", device);
        report.put("scope", "Locally stored records exposed by Android content providers for the current user/profile with granted permissions.");
        report.put("limitations", new JSONArray(Arrays.asList(
            "Private app databases, passwords, account tokens, RCS chats, cloud-only records, other users/work profiles, and deleted data are not exported by this helper.",
            "Zero rows means the provider returned no visible rows; it does not prove the device has no records in another app/account/profile.",
            "The phone can change during export. This is a sequential read, not a transactional snapshot.",
            "Contacts vCards are generated by the device provider. Raw tables retain additional available fields.",
            "Calendar recurrence rules and exceptions are preserved as stored; no arbitrary date window is applied.",
            "OEM and Android restrictions may deny individual providers; review every category and error."
        )));
    }

    public JSONObject run() throws Exception {
        if (output.exists()) throw new IOException("Refusing to reuse an existing export directory");
        if (!output.mkdirs()) throw new IOException("Cannot create export folder. Grant storage permission and check free space: " + output);
        writeJson(new File(output, "run-state.json"), new JSONObject().put("status", "running").put("startedUtc", started));
        table("contacts", "content://com.android.contacts/contacts", new RowAction() {
            public void process(JSONObject row, JSONObject extra) throws Exception {
                String id = identifier(row, "_id");
                String lookup = nullable(row, "lookup");
                extra.put("vcardRequestedFile", "vcards/contact-" + id + ".vcf");
                try {
                    if (lookup == null) throw new IOException("Contact has no lookup key; vCard cannot be requested");
                    String encoded = encodePathSegment(lookup);
                    extra.put("vcard", copy("content://com.android.contacts/contacts/as_vcard/" + encoded, "vcards/contact-" + id + ".vcf"));
                } catch (Exception e) { addError("contacts", "vCard for contact " + id, e); extra.put("vcardError", describe(e)); }
                String photo = nullable(row, "photo_uri");
                if (photo != null) {
                    extra.put("photoRequestedFile", "contact-photos/contact-" + id + ".bin");
                    try { extra.put("photo", copy(photo, "contact-photos/contact-" + id + ".bin")); }
                    catch (Exception e) { addError("contacts", "photo for contact " + id, e); extra.put("photoError", describe(e)); }
                }
            }
        });
        table("raw_contacts", "content://com.android.contacts/raw_contacts", null);
        table("contact_data", "content://com.android.contacts/data", null);
        table("contact_groups", "content://com.android.contacts/groups", null);
        table("contact_settings", "content://com.android.contacts/settings", null);
        table("contact_aggregation_exceptions", "content://com.android.contacts/aggregation_exceptions", null);
        table("contact_profile", "content://com.android.contacts/profile", null);
        table("contact_profile_raw", "content://com.android.contacts/profile/raw_contacts", null);
        table("contact_profile_data", "content://com.android.contacts/profile/data", null);
        table("sim_contacts", "content://icc/adn", null);
        table("sms", "content://sms", null);
        table("mms", "content://mms", new RowAction() {
            public void process(JSONObject row, JSONObject extra) throws Exception {
                String id = identifier(row, "_id");
                extra.put("addresses", "mms-addresses/message-" + id + ".jsonl");
                table("mms_addresses_" + id, "content://mms/" + id + "/addr", "mms-addresses/message-" + id + ".jsonl", null);
            }
        });
        table("mms_parts", "content://mms/part", new RowAction() {
            public void process(JSONObject row, JSONObject extra) throws Exception {
                String id = identifier(row, "_id");
                String type = nullable(row, "ct");
                boolean inlineText = "text/plain".equals(type) || "text/html".equals(type) || "application/smil".equals(type);
                if (inlineText && nullable(row, "_data") == null) {
                    extra.put("attachmentStorage", "Inline text is preserved in values.text; original charset remains in values.chset.");
                } else {
                    extra.put("attachmentRequestedFile", "mms-attachments/part-" + id + ".bin");
                    extra.put("attachment", copy("content://mms/part/" + id, "mms-attachments/part-" + id + ".bin"));
                }
            }
        });
        table("message_threads", "content://mms-sms/conversations?simple=true", null);
        table("message_addresses", "content://mms-sms/canonical-addresses", null);
        table("call_logs", "content://call_log/calls", null);
        table("calendars", "content://com.android.calendar/calendars", null);
        table("calendar_events", "content://com.android.calendar/events", null);
        table("calendar_reminders", "content://com.android.calendar/reminders", null);
        table("calendar_attendees", "content://com.android.calendar/attendees", null);
        table("calendar_extended_properties", "content://com.android.calendar/extendedproperties", null);
        report.put("finishedUtc", now());
        report.put("runFinished", true);
        report.put("status", errors.length() == 0 ? "complete" : "partial");
        report.put("complete", errors.length() == 0);
        report.put("exportedRows", exportedRows);
        report.put("exportedBinaryFiles", exportedFiles);
        report.put("categories", categories);
        report.put("errors", errors);
        // Only this final file certifies that every planned category was attempted.
        writeJson(new File(output, "report.json"), report);
        return report;
    }

    private void table(String category, String uri, RowAction action) {
        table(category, uri, category + ".jsonl", action);
    }

    private void table(String category, String uri, String filename, RowAction action) {
        progress.update("Reading " + category.replace('_', ' ') + "…");
        JSONObject result = new JSONObject();
        long rows = 0;
        int priorErrors = errors.length();
        File destination = new File(output, filename);
        File partial = new File(destination.getPath() + ".partial");
        Cursor cursor = null;
        try {
            result.put("category", category).put("sourceUri", uri).put("file", filename);
            File parent = destination.getParentFile();
            if (!parent.exists() && !parent.mkdirs()) throw new IOException("Cannot create output directory");
            cursor = provider.query(uri);
            if (cursor == null) throw new IOException("Provider returned a null cursor; access could not be verified");
            result.put("providerRowCountAtQuery", cursor.getCount());
            String[] columns = cursor.getColumnNames();
            result.put("columns", new JSONArray(Arrays.asList(columns)));
            try (FileOutputStream raw = new FileOutputStream(partial); BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(raw, "UTF-8"))) {
                while (cursor.moveToNext()) {
                    JSONObject row = new JSONObject();
                    JSONObject extra = new JSONObject();
                    JSONArray fieldErrors = new JSONArray();
                    for (int i = 0; i < columns.length; i++) {
                        try { row.put(columns[i], readValue(cursor, i)); }
                        catch (Exception e) {
                            // Never turn an unreadable field into an indistinguishable SQL NULL.
                            row.put(columns[i], new JSONObject().put("$error", describe(e)));
                            fieldErrors.put(columns[i]);
                            addError(category, "row " + rows + " column " + columns[i], e);
                        }
                    }
                    if (fieldErrors.length() != 0) extra.put("unreadableColumns", fieldErrors);
                    if (action != null) {
                        try { action.process(row, extra); }
                        catch (Exception e) { extra.put("error", describe(e)); addError(category, "row " + rows, e); }
                    }
                    JSONObject envelope = new JSONObject().put("values", row);
                    if (extra.length() != 0) envelope.put("export", extra);
                    writer.write(envelope.toString());
                    writer.newLine();
                    rows++;
                    exportedRows++;
                    if (rows % 500 == 0) progress.update(category.replace('_', ' ') + ": " + rows + " records…");
                }
                writer.flush();
                raw.getFD().sync();
            }
            if (!partial.renameTo(destination)) throw new IOException("Could not finalize " + filename);
            result.put("sha256", hashFile(destination));
            result.put("bytes", destination.length());
            result.put("status", errors.length() == priorErrors ? "complete" : "partial");
        } catch (Exception e) {
            addError(category, uri, e);
            try {
                result.put("status", rows == 0 ? "failed" : "partial");
                result.put("error", describe(e));
                if (partial.exists()) result.put("partialFile", filename + ".partial");
            } catch (Exception impossible) { throw new IllegalStateException(impossible); }
        } finally {
            if (cursor != null) {
                try { cursor.close(); } catch (Exception e) { addError(category, "closing cursor", e); }
            }
            try {
                result.put("exportedRows", rows);
                result.put("errorCount", errors.length() - priorErrors);
                if (errors.length() != priorErrors && "complete".equals(result.optString("status"))) result.put("status", "partial");
                categories.put(result);
            } catch (Exception impossible) { throw new IllegalStateException(impossible); }
        }
    }

    private Object readValue(Cursor cursor, int index) throws Exception {
        switch (cursor.getType(index)) {
            case Cursor.FIELD_TYPE_NULL: return JSONObject.NULL;
            case Cursor.FIELD_TYPE_INTEGER: return cursor.getLong(index);
            case Cursor.FIELD_TYPE_FLOAT: return cursor.getDouble(index);
            case Cursor.FIELD_TYPE_STRING: return cursor.getString(index);
            case Cursor.FIELD_TYPE_BLOB:
                byte[] blob = cursor.getBlob(index);
                return new JSONObject().put("$blob", provider.base64(blob)).put("encoding", "base64").put("bytes", blob.length);
            default: throw new IOException("Unknown cursor field type");
        }
    }

    private JSONObject copy(String uri, String relativePath) throws Exception {
        File destination = new File(output, relativePath);
        File parent = destination.getParentFile();
        if (!parent.exists() && !parent.mkdirs()) throw new IOException("Cannot create attachment folder");
        File partial = new File(destination.getPath() + ".partial");
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        long bytes = 0;
        try (InputStream input = provider.open(uri); FileOutputStream out = new FileOutputStream(partial)) {
            if (input == null) throw new IOException("Provider returned a null attachment stream");
            byte[] buffer = new byte[65536];
            int count;
            while ((count = input.read(buffer)) != -1) {
                if (count == 0) continue;
                out.write(buffer, 0, count);
                digest.update(buffer, 0, count);
                bytes += count;
            }
            out.getFD().sync();
        }
        if (!partial.renameTo(destination)) throw new IOException("Cannot finalize attachment " + relativePath);
        exportedFiles++;
        return new JSONObject().put("file", relativePath).put("bytes", bytes).put("sha256", hex(digest.digest()));
    }

    private void addError(String category, String operation, Exception error) {
        try { errors.put(new JSONObject().put("category", category).put("operation", operation).put("error", describe(error))); }
        catch (Exception impossible) { throw new IllegalStateException(impossible); }
    }
    private static String describe(Exception error) { return error.getClass().getSimpleName() + ": " + String.valueOf(error.getMessage()); }
    private static String nullable(JSONObject row, String key) { return row.isNull(key) ? null : row.optString(key, null); }
    private static String identifier(JSONObject row, String key) throws IOException {
        String value = nullable(row, key);
        if (value == null || !value.matches("[0-9]+")) throw new IOException("Missing or invalid provider record ID");
        return value;
    }
    private static String encodePathSegment(String value) throws Exception { return java.net.URLEncoder.encode(value, "UTF-8").replace("+", "%20"); }
    private static String now() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US);
        format.setTimeZone(TimeZone.getTimeZone("UTC"));
        return format.format(new Date());
    }
    private static String hex(byte[] bytes) {
        StringBuilder result = new StringBuilder();
        for (byte value : bytes) result.append(String.format(Locale.US, "%02x", value & 255));
        return result.toString();
    }
    private static String hashFile(File file) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        try (InputStream input = new FileInputStream(file)) {
            byte[] buffer = new byte[65536];
            int count;
            while ((count = input.read(buffer)) != -1) digest.update(buffer, 0, count);
        }
        return hex(digest.digest());
    }
    private static void writeJson(File file, JSONObject value) throws Exception {
        File temporary = new File(file.getPath() + ".partial");
        try (FileOutputStream raw = new FileOutputStream(temporary); Writer writer = new OutputStreamWriter(raw, "UTF-8")) {
            writer.write(value.toString(2));
            writer.write("\n");
            writer.flush();
            raw.getFD().sync();
        }
        if (!temporary.renameTo(file)) throw new IOException("Cannot finalize " + file.getName());
    }
}
